### ISSUE TITLE
Ui/Ux Test

### ISSUE THREAD

**Issue by OzarUn** [418-Development/client-connect-hub#94]

**Comment by xichen379** [comment]
for each project, could you also add a button to be back to the main page which displays all the projects? @Marc-Beyer

**Comment by xichen379** [comment]
when i sign up by using my own email address then log in , it only shows page as attached @Marc-Beyer 




![Image](https://github.com/418-Development/client-connect-hub/assets/161047624/1c9d7731-44e9-4ef2-8e6d-c48203ccb9ea)

**Comment by Marc-Beyer** [comment]
We will consider adding a back button to the project view. But we will ask the client for feedback first.
